pipeline:
  identifier: Build_JeremyFields_harness_python_1706730295564
  name: Build harness-python
  orgIdentifier: default
  projectIdentifier: test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706730077161
        repoName: JeremyFields/harness-python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  name: Build Python App
                  identifier: build_python_app
                  template:
                    templateRef: BuildPythonApp
                    versionLabel: Version1
              - step:
                  name: Build and push to docker
                  identifier: Build_and_push_to_docker
                  template:
                    templateRef: BuildAndPushDockerhub
                    versionLabel: Version1
                    templateInputs:
                      type: BuildAndPushDockerRegistry
                      spec:
                        repo: <+input>
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
        delegateSelectors:
          - docker-delegate
