pipeline:
  identifier: Build_JeremyFields_harness_python_1706730295564
  name: Build harness-python
  orgIdentifier: default
  projectIdentifier: test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706730077161
        repoName: JeremyFields/harness-python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: Run_pytest
                  name: Run pytest
                  spec:
                    shell: Sh
                    command: |-
                      ls
                      cd tests
                      ls
                      echo "Running tests"
                      if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
                      python -m pytest test_tester.py --junit-xml=output-test.xml
                      reports:
                      type: JUnit
                      spec:
                        paths:
                        output-test.xml
              - step:
                  type: Run
                  identifier: build_python_app
                  name: Build Python App
                  spec:
                    shell: Sh
                    command: |-
                      ls
                      python -m pip install --upgrade pip
                      if [ -f requirements.txt ]; then pip install --ignore-installed -r requirements.txt; fi
              - step:
                  type: BuildAndPushDockerRegistry
                  identifier: Build_and_push_to_docker
                  name: Build and push to docker
                  spec:
                    connectorRef: jeremydocker
                    repo: jboofaloo/harness-test
                    tags:
                      - v1
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
